channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python==3.12
  - pip>=25.0
  - flit>=3.11
  # data science
  - copulae
  - lmoments3
  - numpy>=2.0
  #- numcodecs<=0.15.1
  - openturns>=1.24
  - pandas
  - pyextremes
  - scipy
  - xarray
  - xclim==0.60
  #- xscen>=0.10.1
  - zarr
  # parameters
  - param
  # other:
  - yaml
  - s3fs
  - sphinx