channels:
- https://conda.anaconda.org/conda-forge
- conda-forge
dependencies:
- black==24.1.1
- blackdoc==0.3.9
- bump-my-version>=0.18.3
- coverage>=6.2.0,<7.0.0
- coveralls>=3.3.1
- flake8-rst-docstrings>=0.3.0
- flake8>=6.1.0
- flit=3.9
- isort==5.13.2
- lmoments3
- numpy>=2.0
- openturns
- pandas
- param
- pip=24.0
- pip>=23.1.2
- pre-commit>=3.3.2
- pyextremes
- pytest-cov>=4.0.0
- pytest>=7.3.1
- python>=3.9,<3.12
- s3fs
- scipy
- tox>=4.5.1
- watchdog>=3.0.0
- xarray<2025.3.0
- xclim
- xscen>=0.10.1
- yaml
- zarr<3
