channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- aiofiles
- filelock
- flit=3.9
- gunicorn
- lmoments3
- numpy>=2.0
- openturns
- pandas
- param
- pip=24.0
- pyextremes
- python>=3.9,<3.12
- s3fs
- scipy
- starlette
- uvicorn[standard]
- xarray<2025.3.0
- xclim
- xscen>=0.10.1
- yaml
- zarr<3
