name: peach
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.12,<3.13
  - pip >=25.2
  - flit >=3.11.0,<4.0
  # data science
  - copulae
  - geopandas
  - lmoments3
  - numpy >=2.0
  #- numcodecs <=0.15.1
  - openturns >=1.24,<1.27
  - pandas >=2.0
  - pyextremes
  - scipy >=1.11.0
  - xarray >=2023.11.0,!=2024.10.0
  - xclim ==0.60
  - zarr
  - h5py
  - h5netcdf
  # parameters
  - param
  # other:
  - yaml
  - s3fs
  - sphinx
