channels:
- https://conda.anaconda.org/conda-forge
- bokeh
dependencies:
- aiofiles
- copulae
- filelock
- flit>=3.11
- gunicorn
- hvplot
- ipyleaflet
- ipywidgets_bokeh
- jupyter
- lmoments3
- numpy>=2.0
- openturns>=1.24
- pandas
- panel >= 1.5.5
- param
- pip>=25.0
- pyextremes
- python==3.12
- s3fs
- scipy
- sphinx
- starlette
- uvicorn[standard]
- watchfiles
- xarray
- xclim
- yaml
- zarr
