channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- aiofiles
- copulae
- filelock
- flit>=3.11
- gunicorn
- lmoments3
- numpy>=2.0
- openturns>=1.24
- pandas
- param
- pip>=25.0
- pyextremes
- python==3.12
- s3fs
- scipy
- sphinx
- starlette
- uvicorn[standard]
- xarray
- xclim
- yaml
- zarr
