name: peach-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10,<3.15
  # Dev tools and testing
  - bump-my-version >=1.2.6
  - codespell >=2.4.1
  - coverage >=7.5.0
  - deptry >=0.24.0
  - flake8 >=7.3.0
  - flake8-rst-docstrings >=0.4.0
  - flit >=3.11.0,<4.0
  - mypy >=1.19.1
  - numpydoc >=1.10.0
  - pip >=26.0.1
  - prek >=0.3.0
  - pytest >=9.0.2
  - pytest-cov >=7.0.0
  - ruff >=0.15.0
  - tox >=4.41.0
  - tox-gh >=1.6.1
  - vulture >=2.14
  - watchdog >=6.0.0
