icon:
  pr:
    name: tint
    marker_color: blue
    button_color: "#37a8da"
    icon_color: white
    spin: False
    angle: 45
  tas:
    name: thermometer-three-quarters
    marker_color: red
    button_color: "#c93a27"
    icon_color: white
    spin: False
    angle: -45
  wl:
    name: anchor
    marker_color: darkblue
    button_color: "#00619a"
    icon_color: white
    spin: False
    angle: 0
  idf:
    name: umbrella
    marker_color: green
    button_color: "#72af26"
    icon_color: white
    spin: False
    angle: 0
map:
  center:
    - 45.508
    - -73.562
  zoom: 7
site:
  lat: 45.5
  lon: -73.5
  radius: 50
map_layout:
  display: "flex"
  flex_flow: "column"
  width: "100%"
  height: "500px"
pre_map_layout:
  height: 500
  sizing_mode: "stretch_width"
marker_cluster:
  disable_clustering_at_zoom: 10
  remove_outside_visible_bounds: False
  animate_adding_markers: False
  animate: False
  show_coverage_on_hover: False
  spiderfy_on_max_zoom: False
initial_bounds:
  - [44.65, -75.2]
  - [46.65, -65.2]
table:
  columns:
    - station
    - station_name
    - lat
    - lon
    - valid_months
    - start
    - end
    - distance
